import { motion } from "framer-motion";
import { useAuthState } from "react-firebase-hooks/auth";
import { FaDumbbell, FaHeartbeat, FaAppleAlt } from "react-icons/fa";
import { useNavigate } from "react-router-dom";
import { auth } from "../firebaseConfig";

export const Hero = () => {
  const navigate = useNavigate();
  const [user] = useAuthState(auth);

  return (
    <>
      <section
        id="home"
        className="flex flex-col items-center justify-center  text-center h-[85vh]"
      >
        <motion.div
          className="p-10 rounded-md"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1 }}
        >
          <h1 className="text-4xl sm:text-6xl font-semibold">
            AI Powered Gym Guide
          </h1>
          <p className="text-lg sm:text-2xl mt-4">
            Transform Your Workout and Diet with AI
          </p>

          <div className="absolute top-36 -left-10 md:left-20 md:w-[72vh] md:h-[72vh] w-[30vh] h-[30vh] bg-purple-200 rounded-full opacity-40 mix-blend-multiply filter blur-3xl animate-blob animation-delay-4000"></div>

          <div className="absolute top-[80%] right-10 md:w-[72vh] md:h-[72vh] w-[30vh] h-[30vh] bg-orange-200 rounded-full opacity-30 mix-blend-multiply filter blur-3xl animate-blob animation-delay-4000"></div>

          <div className="absolute top-[150%] -left-10 md:w-[72vh] md:h-[72vh] w-[30vh] h-[30vh] bg-blue-200 rounded-full opacity-30 mix-blend-multiply filter blur-3xl animate-blob animation-delay-4000"></div>

          <div className="absolute top-[250%] right-60 md:w-[72vh] md:h-[72vh] w-[30vh] h-[30vh] bg-red-200 rounded-full opacity-30 mix-blend-multiply filter blur-3xl animate-blob animation-delay-4000"></div>

          <motion.button
            className="mt-6 px-6 py-3 bg-gray-800 text-white rounded-full hover:bg-gray-700"
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            onClick={() => navigate("/login")}
          >
            {user ? "Dashboard" : "Get Started Now"}
          </motion.button>
        </motion.div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20">
        <div className="container mx-auto text-center">
          <motion.h2
            className="text-3xl sm:text-4xl font-bold"
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.5 }}
          >
            Our Features
          </motion.h2>
          <div className="mt-10 flex flex-wrap justify-around">
            {[
              {
                icon: <FaDumbbell size={40} />,
                title: "AI Workout Plans",
                description:
                  "Personalized workout plans generated by AI to match your fitness goals.",
              },
              {
                icon: <FaHeartbeat size={40} />,
                title: "Health Monitoring",
                description:
                  "Track your health metrics and progress with advanced AI tools.",
              },
              {
                icon: <FaAppleAlt size={40} />,
                title: "AI Diet Plans",
                description:
                  "Get customized diet plans based on your preferences and goals.",
              },
            ].map((feature, index) => (
              <motion.div
                key={index}
                className="bg-gray-200/30 p-6 m-4 rounded-md shadow-md w-full sm:w-1/3"
                whileHover={{ scale: 1.05 }}
              >
                <div className="text-center mb-4">{feature.icon}</div>
                <h3 className="text-lg sm:text-2xl font-semibold">
                  {feature.title}
                </h3>
                <p className="mt-2 text-sm">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section id="how-it-works" className="py-20">
        <div className="container mx-auto text-center">
          <motion.h2
            className="text-3xl sm:text-4xl font-bold"
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.5 }}
          >
            How It Works
          </motion.h2>
          <div className="mt-10 flex flex-wrap justify-around items-center">
            {[
              {
                step: "1",
                title: "Sign Up",
                description: "Create your profile and set your fitness goals.",
              },
              {
                step: "2",
                title: "Get Your Plan",
                description: "Receive your AI-generated workout and diet plan.",
              },
              {
                step: "3",
                title: "Start Training",
                description:
                  "Follow your personalized plan and track your progress.",
              },
            ].map((item, index) => (
              <motion.div
                key={index}
                className="bg-gray-200/40 backdrop-blur-sm p-6 m-4 rounded-md shadow-md w-full sm:w-1/3"
                whileHover={{ scale: 1.05 }}
              >
                <div className="text-3xl font-bold mb-4">{item.step}</div>
                <h3 className="text-lg sm:text-xl font-semibold">
                  {item.title}
                </h3>
                <p className="mt-2 text-sm">{item.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Call to Action Section */}
      <section id="cta" className="py-20">
        <div className="container mx-auto text-center">
          <motion.h2
            className="text-3xl sm:text-4xl font-bold"
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.5 }}
          >
            Ready to Transform Your Life?
          </motion.h2>
          <motion.button
            className="mt-6 px-6 py-3 bg-gray-800 text-white rounded-full hover:bg-gray-700"
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            onClick={() => navigate("/sign-up")}
          >
            {user ? "Dashboard" : "Register"}
          </motion.button>
        </div>
      </section>
    </>
  );
};
